
const PRESETS = {
  "Modern Pop": { targetBands:[0.58,0.62,0.57,0.50,0.56,0.61,0.64,0.60], notes:"Assinatura moderna, controlada e brilhante." },
  "Gospel Worship": { targetBands:[0.55,0.63,0.60,0.54,0.58,0.59,0.56,0.50], notes:"Médios cheios, graves firmes e brilho equilibrado." },
  "Broadcast": { targetBands:[0.42,0.45,0.52,0.62,0.66,0.60,0.50,0.42], notes:"Foco em inteligibilidade e centro." },
  "Cinematic": { targetBands:[0.67,0.66,0.58,0.48,0.47,0.55,0.60,0.62], notes:"Subgrave e espaço mais amplos." },
  "Vocal Bright": { targetBands:[0.38,0.44,0.48,0.58,0.70,0.72,0.64,0.58], notes:"Ênfase em presença e ar." },
  "Master Loud": { targetBands:[0.54,0.56,0.54,0.53,0.57,0.59,0.59,0.55], notes:"Perfil de master denso e competitivo." }
};
const BAND_NAMES = ["Sub","Bass","Low-Mid","Mid","Upper Mid","Presence","Brilliance","Air"];
const BAND_LABELS = ["20-60","60-120","120-300","300-1k","1k-3k","3k-6k","6k-12k","12k-20k"];
const STRICTNESS = { soft:1.25, normal:1.0, strict:0.78 };
const q = (id) => document.getElementById(id);
const fileInput=q("fileInput"), presetSelect=q("presetSelect"), analysisMode=q("analysisMode"), strictnessSelect=q("strictnessSelect"),
  analyzeBtn=q("analyzeBtn"), exportBtn=q("exportBtn"), installBtn=q("installBtn"), helpBtn=q("helpBtn"),
  installStatus=q("installStatus"), audioPlayer=q("audioPlayer"), statusText=q("statusText"), reportEl=q("report"),
  summaryCards=q("summaryCards"), actionCards=q("actionCards"), recipeCards=q("recipeCards"), timelineDetails=q("timelineDetails");
const peakValue=q("peakValue"), rmsValue=q("rmsValue"), crestValue=q("crestValue"), stereoValue=q("stereoValue"),
  sibilanceValue=q("sibilanceValue"), saturationValue=q("saturationValue"), maskingValue=q("maskingValue"), reverbValue=q("reverbValue");
const bandCanvas=q("bandChart"), fftCanvas=q("fftChart"), effectCanvas=q("effectChart"), deltaCanvas=q("deltaChart"),
  timelineCanvas=q("timelineChart"), matrixCanvas=q("matrixChart");
let currentFile=null, currentResult=null, engine=null, deferredPrompt=null;
Object.keys(PRESETS).forEach(name=>{const o=document.createElement("option");o.value=name;o.textContent=name;presetSelect.appendChild(o);});
if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./service-worker.js").catch(()=>{}));}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.disabled=false;installStatus.textContent="Pronto para instalar no Android.";});
window.addEventListener("appinstalled",()=>{installStatus.textContent="MasterCheck instalado no dispositivo.";installBtn.disabled=true;});
installBtn.addEventListener("click",async()=>{if(!deferredPrompt){installStatus.textContent="Publique em HTTPS e abra no Chrome do Android.";return;}deferredPrompt.prompt();const c=await deferredPrompt.userChoice;installStatus.textContent=c.outcome==="accepted"?"Instalação aceita.":"Instalação cancelada.";deferredPrompt=null;installBtn.disabled=true;});
helpBtn.addEventListener("click",()=>{installStatus.textContent="Para instalar: publique em HTTPS e abra no Chrome Android.";});
fileInput.addEventListener("change",async e=>{currentFile=e.target.files[0]||null;currentResult=null;clearOutputs();if(!currentFile){statusText.textContent="Aguardando arquivo...";return;}audioPlayer.src=URL.createObjectURL(currentFile);statusText.textContent=`Arquivo selecionado: ${currentFile.name}. Preparando análise...`;try{await ensureEngine();await waitForAudioReadiness(audioPlayer);statusText.textContent="Áudio pronto para análise.";}catch(error){statusText.textContent="Não foi possível preparar este áudio. "+error.message;}});
analyzeBtn.addEventListener("click",async()=>{if(!currentFile)return alert("Carregue um arquivo primeiro.");try{await ensureEngine();await waitForAudioReadiness(audioPlayer);statusText.textContent="Analisando áudio por múltiplos trechos...";analyzeBtn.disabled=true;currentResult=await analyzeWithMediaElement(audioPlayer,presetSelect.value,analysisMode.value,strictnessSelect.value);renderMetrics(currentResult);drawBandComparison(bandCanvas,currentResult.bandLevels,currentResult.targetBands,currentResult.presetName);drawFFTChart(fftCanvas,currentResult.fftCurve,currentResult.targetCurve);drawEffectChart(effectCanvas,currentResult.effects);drawDeltaChart(deltaCanvas,currentResult.bandDelta);drawTimelineChart(timelineCanvas,currentResult.timelineSegments);drawMatrixChart(matrixCanvas,currentResult);renderActionCards(currentResult.actionPlan);renderRecipeCards(currentResult.recipes);renderTimelineDetails(currentResult.timelineSegments);renderReport(currentResult);statusText.textContent="Análise concluída com sucesso.";}catch(error){statusText.textContent="Falha ao analisar este arquivo. "+error.message;}finally{analyzeBtn.disabled=false;}});
exportBtn.addEventListener("click",()=>{if(!currentResult)return alert("Analise o áudio antes de exportar.");const lines=["MasterCheck","Relatório técnico","",`Preset: ${currentResult.presetName}`,`Modo: ${currentResult.mode}`,`Rigor: ${currentResult.strictness}`,"","Ações recomendadas:"];currentResult.actionPlan.forEach(a=>lines.push(`- [${a.priority}] ${a.title}: ${a.description}`));lines.push("","Receitas de correção:");currentResult.recipes.forEach(r=>lines.push(`- ${r.title}: ${r.description}`));lines.push("","Diagnóstico:");currentResult.reportLines.forEach(line=>lines.push("- "+line.replace(/<[^>]+>/g,"")));const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.join("\\n")],{type:"text/plain;charset=utf-8"}));a.download="mastercheck_relatorio.txt";a.click();});
async function ensureEngine(){if(engine)return engine;const AudioCtx=window.AudioContext||window.webkitAudioContext;const ctx=new AudioCtx();const analyser=ctx.createAnalyser();analyser.fftSize=2048;analyser.smoothingTimeConstant=0.72;const source=ctx.createMediaElementSource(audioPlayer);source.connect(analyser);analyser.connect(ctx.destination);engine={ctx,analyser,freqData:new Uint8Array(analyser.frequencyBinCount),timeData:new Uint8Array(analyser.fftSize)};return engine;}
function waitForAudioReadiness(media){return new Promise((resolve,reject)=>{if(media.readyState>=2&&Number.isFinite(media.duration))return resolve();const done=()=>{cleanup();resolve();},fail=()=>{cleanup();reject(new Error("arquivo não suportado pelo navegador"));},cleanup=()=>{media.removeEventListener("loadedmetadata",done);media.removeEventListener("canplay",done);media.removeEventListener("error",fail);};media.addEventListener("loadedmetadata",done);media.addEventListener("canplay",done);media.addEventListener("error",fail);});}
async function analyzeWithMediaElement(media,presetName,mode,strictness){const preset=PRESETS[presetName],ctx=engine.ctx;if(ctx.state==="suspended")await ctx.resume();const duration=media.duration||0;if(!Number.isFinite(duration)||duration<=0)throw new Error("duração inválida");const points=duration<6?[duration*.2,duration*.5,duration*.8].map(v=>Math.max(0,Math.min(duration,v))):[.06,.18,.32,.48,.64,.80,.92].map(r=>duration*r);const curves=[],waves=[],timelineSegments=[];let peak=0,rmsAccum=0,stereoProxyAccum=0;const originalTime=media.currentTime||0,originalMuted=media.muted,originalVolume=media.volume;media.muted=true;media.volume=0;for(let idx=0;idx<points.length;idx++){await seekTo(media,points[idx]);try{await media.play();}catch(e){}await delay(220);const curve=captureFrequencyCurve(engine.analyser,engine.freqData),wave=captureWaveform(engine.analyser,engine.timeData);curves.push(curve);waves.push(wave);const p=computePeakFromTime(wave),r=computeRMSFromTime(wave);peak=Math.max(peak,p);rmsAccum+=r;stereoProxyAccum+=estimateStereoProxy(curve);media.pause();timelineSegments.push(buildSegmentDiagnostics(curve,wave,idx,points.length,preset,mode,strictness));}media.currentTime=Math.min(originalTime,media.duration||originalTime);media.muted=originalMuted;media.volume=originalVolume;const avgCurve=averageCurves(curves),avgWave=averageWaveforms(waves),bandLevels=computeBandsFromCurve(avgCurve),normalizedBands=normalizeBands(bandLevels),targetBands=adaptTargetBands(preset.targetBands,mode),targetCurve=buildTargetCurve(targetBands,avgCurve.length),bandDelta=normalizedBands.map((v,i)=>v-targetBands[i]);const rms=rmsAccum/Math.max(points.length,1),peakDb=linearToDb(Math.max(peak,1e-6)),rmsDb=linearToDb(Math.max(rms,1e-6)),crestFactor=peakDb-rmsDb,stereoWidth=clamp(stereoProxyAccum/Math.max(points.length,1),0,1),effects=detectEffects({avgWave,peak,crestFactor,stereoWidth,bandLevels:normalizedBands,targetBands,strictness}),actionPlan=buildActionPlan(effects,bandDelta,timelineSegments),recipes=buildCorrectionRecipes(effects,bandDelta),reportLines=buildReport({preset,presetName,mode,strictness,stereoWidth,normalizedBands,targetBands,bandDelta,effects,timelineSegments,actionPlan,recipes});return{presetName,mode,strictness,peakDb,rmsDb,crestFactor,stereoWidth,fftCurve:avgCurve,targetCurve,bandLevels:normalizedBands,targetBands,bandDelta,effects,reportLines,timelineSegments,actionPlan,recipes};}
function seekTo(media,time){return new Promise((resolve,reject)=>{const ok=()=>{cleanup();setTimeout(resolve,90);},fail=()=>{cleanup();reject(new Error("falha ao posicionar no trecho"));},cleanup=()=>{media.removeEventListener("seeked",ok);media.removeEventListener("error",fail);};media.addEventListener("seeked",ok);media.addEventListener("error",fail);media.currentTime=Math.min(Math.max(0,time),Math.max(0,media.duration||time));});}
function delay(ms){return new Promise(r=>setTimeout(r,ms));}
function captureFrequencyCurve(analyser,arr){analyser.getByteFrequencyData(arr);return Float32Array.from(arr,v=>v/255);}
function captureWaveform(analyser,arr){analyser.getByteTimeDomainData(arr);return Float32Array.from(arr,v=>(v-128)/128);}
function computePeakFromTime(wave){let p=0;for(const v of wave)p=Math.max(p,Math.abs(v));return p;}
function computeRMSFromTime(wave){let s=0;for(const v of wave)s+=v*v;return Math.sqrt(s/Math.max(wave.length,1));}
function averageCurves(curves){const len=curves[0]?.length||0,out=new Float32Array(len);for(const c of curves)for(let i=0;i<len;i++)out[i]+=c[i];for(let i=0;i<len;i++)out[i]/=Math.max(curves.length,1);return out;}
function averageWaveforms(waves){const len=waves[0]?.length||0,out=new Float32Array(len);for(const w of waves)for(let i=0;i<len;i++)out[i]+=w[i];for(let i=0;i<len;i++)out[i]/=Math.max(waves.length,1);return out;}
function computeBandsFromCurve(curve){const ranges=[[0,.03],[.03,.07],[.07,.15],[.15,.30],[.30,.50],[.50,.68],[.68,.88],[.88,1]];return ranges.map(([a,b])=>{const start=Math.floor(curve.length*a),end=Math.max(start+1,Math.floor(curve.length*b));let sum=0,count=0;for(let i=start;i<end;i++){sum+=curve[i];count++;}return count?sum/count:0;});}
function normalizeBands(levels){const max=Math.max(...levels,1e-9);return levels.map(v=>v/max);}
function adaptTargetBands(targetBands,mode){const a=[...targetBands];if(mode==="mastering"){a[0]+=0.02;a[1]+=0.02;a[5]+=0.02;a[6]+=0.02;}else if(mode==="vocal"){a[4]+=0.05;a[5]+=0.05;a[6]+=0.03;a[0]-=0.05;a[1]-=0.03;}else if(mode==="broadcast"){a[3]+=0.04;a[4]+=0.06;a[0]-=0.05;a[7]-=0.05;}return a.map(v=>clamp(v,0.2,0.9));}
function buildTargetCurve(targetBands,length){const out=new Float32Array(length);for(let i=0;i<length;i++)out[i]=targetBands[Math.min(targetBands.length-1,Math.floor((i/length)*targetBands.length))];return out;}
function estimateStereoProxy(curve){const high=averageSlice(curve,.45,.95),low=averageSlice(curve,0,.18);return clamp(.35+(high-low)*.8,.12,.85);}
function averageSlice(arr,a,b){const start=Math.floor(arr.length*a),end=Math.max(start+1,Math.floor(arr.length*b));let sum=0,count=0;for(let i=start;i<end;i++){sum+=arr[i];count++;}return count?sum/count:0;}
function detectEffects({avgWave,peak,crestFactor,stereoWidth,bandLevels,targetBands,strictness}){const mult=STRICTNESS[strictness]||1,sibilance=scoreFromDifference(avgBand(bandLevels,5,6),avgBand(targetBands,5,6),.08*mult),harshness=scoreFromDifference(avgBand(bandLevels,4,5),avgBand(targetBands,4,5),.08*mult),mud=scoreFromDifference(avgBand(bandLevels,1,2),avgBand(targetBands,1,2),.09*mult),subExcess=scoreFromDifference(bandLevels[0],targetBands[0],.08*mult),compression=clamp(mapRange(12-crestFactor,-2,8*mult,0,100),0,100),saturation=clamp(mapRange(peak-.88,-.1,.12*mult,0,100),0,100),reverb=estimateReverb(avgWave),stereo=clamp(stereoWidth*140,0,100),transient=clamp(mapRange(crestFactor,6,16,0,100),0,100),masking=clamp((mud*.45)+(compression*.20)+(reverb*.15)+(harshness*.20),0,100),brightness=scoreFromDifference(avgBand(bandLevels,6,7),avgBand(targetBands,6,7),.08*mult);return{sibilance,harshness,mud,subExcess,compression,saturation,reverb,stereo,transient,masking,brightness};}
function estimateReverb(wave){let smooth=0;for(let i=1;i<wave.length;i++)smooth+=1-Math.min(Math.abs(wave[i]-wave[i-1])/.20,1);smooth/=Math.max(wave.length-1,1);return clamp(smooth*100,0,100);}
function avgBand(arr,s,e){let sum=0,count=0;for(let i=s;i<=e;i++){sum+=arr[i];count++;}return count?sum/count:0;}
function scoreFromDifference(actual,target,tolerance){return clamp(((actual-target)/tolerance)*40+50,0,100);}
function mapRange(value,inMin,inMax,outMin,outMax){const n=(value-inMin)/(inMax-inMin);return outMin+n*(outMax-outMin);}
function clamp(value,min,max){return Math.min(max,Math.max(min,value));}
function linearToDb(v){return 20*Math.log10(v);}
function buildSegmentDiagnostics(curve,wave,index,total,preset,mode,strictness){const bandLevels=normalizeBands(computeBandsFromCurve(curve)),targetBands=adaptTargetBands(preset.targetBands,mode),peak=computePeakFromTime(wave),crest=linearToDb(Math.max(peak,1e-6))-linearToDb(Math.max(computeRMSFromTime(wave),1e-6)),effects=detectEffects({avgWave:wave,peak,crestFactor:crest,stereoWidth:estimateStereoProxy(curve),bandLevels,targetBands,strictness});const severity=Math.max(effects.sibilance,effects.harshness,effects.mud,effects.compression,effects.reverb,effects.masking,effects.saturation);let label="estável";if(effects.sibilance>68)label="sibilância";else if(effects.mud>68)label="low-mid";else if(effects.compression>68)label="compressão";else if(effects.reverb>72)label="reverb";else if(effects.masking>70)label="masking";else if(effects.saturation>65)label="saturação";return{index,label,severity,position:`Trecho ${index+1}/${total}`,effects};}
function buildActionPlan(effects,bandDelta,timeline){const actions=[];const add=(priority,title,description)=>actions.push({priority,title,description});const biggestBand=bandDelta.reduce((best,v,i)=>Math.abs(v)>Math.abs(best.value)?{index:i,value:v}:best,{index:0,value:bandDelta[0]||0});if(effects.sibilance>60)add("Crítico","Controlar sibilância","Teste de-esser entre 5 kHz e 9 kHz, principalmente nos trechos mais agudos.");if(effects.compression>65)add("Crítico","Revisar compressão","Reduza compressão no bus/master ou alivie redução de ganho para recuperar dinâmica.");if(effects.saturation>60)add("Crítico","Reduzir saturação","Baixe ganho em estágios anteriores e confira limiter/clipper.");if(effects.mud>60)add("Importante","Limpar low-mid","Avalie corte suave entre 120 Hz e 300 Hz para reduzir embolo.");if(effects.reverb>68)add("Importante","Enxugar ambiência","Reduza tail ou filtre graves/agudos do reverb para aumentar definição.");if(effects.masking>62)add("Importante","Separar elementos","Reveja arranjo tonal e espaço entre médios e presença.");add("Ajuste fino","Checar maior diferença tonal",`A maior diferença está em ${BAND_NAMES[biggestBand.index]} (${BAND_LABELS[biggestBand.index]}).`);const hottest=timeline.reduce((best,s)=>s.severity>best.severity?s:best,timeline[0]||{severity:0,label:"estável",position:"-"});if(hottest&&hottest.severity>60)add("Ajuste fino","Conferir trecho mais crítico",`${hottest.position} mostra maior atenção em ${hottest.label}.`);return actions.slice(0,6);}
function buildCorrectionRecipes(effects,bandDelta){const recipes=[];const add=(title,description)=>recipes.push({title,description});if(effects.mud>58)add("Receita low-mid","Tente reduzir 1.5 dB a 3 dB entre 180 Hz e 320 Hz com Q médio.");if(effects.sibilance>58)add("Receita de-esser","Teste threshold moderado em 6 kHz a 8.5 kHz.");if(effects.harshness>58)add("Receita upper-mid","Experimente suavizar 2.5 kHz a 4.5 kHz em pequenas doses.");if(effects.reverb>65)add("Receita de ambiência","Reduza tail e filtre graves do reverb para abrir definição.");if(effects.compression>65)add("Receita dinâmica","Relaxe release e reduza redução de ganho no bus/master.");const biggestBand=bandDelta.reduce((best,v,i)=>Math.abs(v)>Math.abs(best.value)?{index:i,value:v}:best,{index:0,value:bandDelta[0]||0});add("Receita tonal principal",`Priorize ajuste em ${BAND_NAMES[biggestBand.index]} (${BAND_LABELS[biggestBand.index]}).`);return recipes.slice(0,6);}
function renderMetrics(result){peakValue.textContent=`${result.peakDb.toFixed(1)} dBFS`;rmsValue.textContent=`${result.rmsDb.toFixed(1)} dBFS`;crestValue.textContent=`${result.crestFactor.toFixed(1)} dB`;stereoValue.textContent=`${(result.stereoWidth*100).toFixed(0)}%`;sibilanceValue.textContent=`${result.effects.sibilance.toFixed(0)}%`;saturationValue.textContent=`${result.effects.saturation.toFixed(0)}%`;maskingValue.textContent=`${result.effects.masking.toFixed(0)}%`;reverbValue.textContent=`${result.effects.reverb.toFixed(0)}%`;const cards=[["Preset",result.presetName],["Modo",result.mode],["Rigor",result.strictness],["Harshness",`${result.effects.harshness.toFixed(0)}%`],["Punch",`${result.effects.transient.toFixed(0)}%`],["Brilho",`${result.effects.brightness.toFixed(0)}%`]];summaryCards.innerHTML=cards.map(([tag,value])=>`<div class="summary-card"><div class="tag">${tag}</div><div class="value">${value}</div></div>`).join("");}
function renderActionCards(actions){actionCards.innerHTML=actions.map(a=>`<div class="action-card"><div class="tag">${a.priority}</div><div class="value">${a.title}</div><div class="desc">${a.description}</div></div>`).join("");}
function renderRecipeCards(recipes){recipeCards.innerHTML=recipes.map(r=>`<div class="action-card"><div class="tag">Receita</div><div class="value">${r.title}</div><div class="desc">${r.description}</div></div>`).join("");}
function renderTimelineDetails(segments){timelineDetails.innerHTML=segments.map(s=>`<div class="timeline-detail"><div class="tag">${s.position}</div><div class="value">${s.label}</div><div class="desc">Severidade: ${Math.round(s.severity)}%</div></div>`).join("");}
function renderReport(result){reportEl.innerHTML=`<div class="section-title">Resumo</div><p>Preset interno selecionado: <strong>${result.presetName}</strong>. Modo: <strong>${result.mode}</strong>. Rigor do comparativo: <strong>${result.strictness}</strong>.</p><div class="section-title">Diagnóstico</div><ul>${result.reportLines.map(line=>`<li>${line}</li>`).join("")}</ul><div class="section-title">Observação</div><p>Esta build adiciona motor interno de decisão, receitas de correção e leitura geral do estado do áudio.</p>`;}
function buildReport({preset,presetName,mode,strictness,stereoWidth,normalizedBands,targetBands,bandDelta,effects,timelineSegments,actionPlan,recipes}){const lines=[];lines.push(`Assinatura do preset: ${preset.notes}`);const biggestBand=bandDelta.reduce((best,v,i)=>Math.abs(v)>Math.abs(best.value)?{index:i,value:v}:best,{index:0,value:bandDelta[0]||0});const hottest=timelineSegments.reduce((best,s)=>s.severity>best.severity?s:best,timelineSegments[0]||{position:"-",label:"estável",severity:0});if(effects.mud>62)lines.push(`<span class="warn">Há indício de acúmulo em low-mid.</span> Teste limpeza entre 120 Hz e 300 Hz.`);else lines.push(`<span class="ok">A região de low-mid está relativamente controlada.</span>`);if(effects.sibilance>60)lines.push(`<span class="warn">A leitura aponta sibilância acima do alvo interno.</span> Vale testar de-esser entre 5 kHz e 9 kHz.`);if(effects.harshness>62)lines.push(`<span class="warn">Há agressividade em upper-mid/presença.</span> Revise entre 2 kHz e 6 kHz.`);if(effects.brightness>65)lines.push(`<span class="info">O brilho/ar está acima da meta interna.</span> Verifique 6 kHz a 16 kHz.`);if(effects.subExcess>60)lines.push(`<span class="warn">O subgrave está acima do alvo.</span> Confira 20 Hz a 60 Hz.`);if(effects.compression>65)lines.push(`<span class="danger">A dinâmica parece comprimida demais.</span> Avalie ataque, release e redução de ganho.`);else if(effects.transient>68)lines.push(`<span class="ok">Transientes preservados.</span> O áudio mantém boa sensação de punch.`);if(effects.saturation>60)lines.push(`<span class="danger">Há risco de saturação/clipping perceptível.</span> Revise limite de pico.`);if(effects.reverb>70)lines.push(`<span class="warn">A textura sugere ambiência/reverb elevada.</span> Veja se a definição foi prejudicada.`);if(effects.masking>62)lines.push(`<span class="warn">Há indício de mascaramento.</span> A sobreposição tonal pode esconder elementos importantes.`);if(stereoWidth<.22)lines.push(`A imagem estéreo está estreita para o preset ${presetName}.`);else if(stereoWidth>.7)lines.push(`A imagem estéreo está ampla. Confira compatibilidade mono e centro.`);lines.push(`Maior diferença tonal detectada: <strong>${BAND_NAMES[biggestBand.index]}</strong> (${BAND_LABELS[biggestBand.index]}), com ${biggestBand.value>0?"excesso":"falta"} relativo à meta.`);lines.push(`Trecho mais crítico: <strong>${hottest.position}</strong>, com foco principal em <strong>${hottest.label}</strong>.`);lines.push(`Ações priorizadas: ${actionPlan.map(a=>`${a.priority}: ${a.title}`).join(" | ")}.`);lines.push(`Receitas geradas: ${recipes.map(r=>r.title).join(" | ")}.`);lines.push(`Configuração aplicada: modo ${mode} com rigor ${strictness}.`);return lines;}
function clearOutputs(){peakValue.textContent="--";rmsValue.textContent="--";crestValue.textContent="--";stereoValue.textContent="--";sibilanceValue.textContent="--";saturationValue.textContent="--";maskingValue.textContent="--";reverbValue.textContent="--";summaryCards.innerHTML="";actionCards.innerHTML="";recipeCards.innerHTML="";timelineDetails.innerHTML="";reportEl.innerHTML="";[bandCanvas,fftCanvas,effectCanvas,deltaCanvas,timelineCanvas,matrixCanvas].forEach(c=>c.getContext("2d").clearRect(0,0,c.width,c.height));}
function drawBackdrop(ctx,w,h){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,"#101723");g.addColorStop(1,"#0b1119");ctx.fillStyle=g;ctx.fillRect(0,0,w,h);}
function drawGrid(ctx,x,y,w,h,lines){ctx.strokeStyle="rgba(255,255,255,.08)";ctx.lineWidth=1;for(let i=0;i<=lines;i++){const yy=y+(i/lines)*h;ctx.beginPath();ctx.moveTo(x,yy);ctx.lineTo(x+w,yy);ctx.stroke();}for(let i=0;i<=8;i++){const xx=x+(i/8)*w;ctx.beginPath();ctx.moveTo(xx,y);ctx.lineTo(xx,y+h);ctx.stroke();}}
function drawLine(ctx,arr,color,x,y,w,h,lineWidth){ctx.strokeStyle=color;ctx.lineWidth=lineWidth;ctx.beginPath();arr.forEach((v,i)=>{const px=x+(i/(arr.length-1))*w,py=y+h-v*h;if(i===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);});ctx.stroke();}
function normalizeArray(arr){const max=Math.max(...arr,1e-9);return Array.from(arr).map(v=>v/max);}
function legend(ctx,x,y,items){ctx.font="13px Arial";items.forEach((item,index)=>{const yy=y+index*22;ctx.fillStyle=item[1];ctx.fillRect(x,yy-10,16,10);ctx.fillStyle="#dce6f9";ctx.fillText(item[0],x+24,yy);});}
function drawBandComparison(canvas,actualBands,targetBands,title){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);drawBackdrop(ctx,w,h);const m=60,cw=w-m*2,ch=h-m*2,step=cw/actualBands.length;drawGrid(ctx,m,m,cw,ch,5);ctx.fillStyle="#dce6f9";ctx.font="14px Arial";ctx.fillText(`Preset interno: ${title}`,m,28);actualBands.forEach((v,i)=>{const x=m+i*step+step*.15,bw=step*.28,y=m+ch-v*ch;ctx.fillStyle="rgba(83,216,251,.85)";ctx.fillRect(x,y,bw,v*ch);const tx=x+bw+step*.08,ty=m+ch-targetBands[i]*ch;ctx.fillStyle="rgba(123,255,178,.92)";ctx.fillRect(tx,ty,bw,targetBands[i]*ch);});legend(ctx,w-250,24,[["Atual","rgba(83,216,251,.85)"],["Referência interna","rgba(123,255,178,.92)"]]);}
function drawFFTChart(canvas,curve,targetCurve){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);drawBackdrop(ctx,w,h);const m=58,cw=w-m*2,ch=h-m*2;drawGrid(ctx,m,m,cw,ch,6);drawLine(ctx,normalizeArray(targetCurve),"rgba(123,255,178,.95)",m,m,cw,ch,2.5);drawLine(ctx,normalizeArray(curve),"rgba(83,216,251,.95)",m,m,cw,ch,2.5);ctx.fillStyle="#dce6f9";ctx.font="14px Arial";ctx.fillText("Curva atual x curva alvo interna",m,28);}
function drawEffectChart(canvas,effects){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);drawBackdrop(ctx,w,h);const entries=[["Compressão",effects.compression],["Sibilância",effects.sibilance],["Reverb",effects.reverb],["Saturação",effects.saturation],["Harshness",effects.harshness],["Masking",effects.masking],["Punch",effects.transient],["Brilho",effects.brightness]],m=60,cw=w-m*2,ch=h-m*2,step=cw/entries.length;drawGrid(ctx,m,m,cw,ch,5);entries.forEach((e,i)=>{const x=m+i*step+step*.14,bw=step*.68,y=m+ch-(e[1]/100)*ch,grad=ctx.createLinearGradient(0,y,0,m+ch);grad.addColorStop(0,"#53d8fb");grad.addColorStop(1,"#1373d4");ctx.fillStyle=grad;ctx.fillRect(x,y,bw,(e[1]/100)*ch);ctx.fillStyle="#dce6f9";ctx.fillText(`${Math.round(e[1])}%`,x+6,y-8);});ctx.fillStyle="#dce6f9";ctx.font="14px Arial";ctx.fillText("Mapa de indícios e intensidade relativa",m,28);}
function drawDeltaChart(canvas,deltas){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);drawBackdrop(ctx,w,h);const m=60,cw=w-m*2,ch=h-m*2,my=m+ch/2,step=cw/deltas.length;drawGrid(ctx,m,m,cw,ch,4);ctx.strokeStyle="rgba(255,255,255,.18)";ctx.beginPath();ctx.moveTo(m,my);ctx.lineTo(m+cw,my);ctx.stroke();deltas.forEach((v,i)=>{const x=m+i*step+step*.18,bw=step*.64,amp=Math.min(Math.abs(v)/.45,1)*(ch/2),y=v>=0?my-amp:my;ctx.fillStyle=v>=0?"rgba(255,107,107,.85)":"rgba(123,255,178,.85)";ctx.fillRect(x,y,bw,amp);});ctx.fillStyle="#dce6f9";ctx.font="14px Arial";ctx.fillText("Acima da meta / abaixo da meta",m,28);}
function drawTimelineChart(canvas,segments){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);drawBackdrop(ctx,w,h);const m=50,cw=w-m*2,ch=h-m*2,step=cw/Math.max(segments.length,1);drawGrid(ctx,m,m,cw,ch,4);segments.forEach((s,i)=>{const x=m+i*step+step*.12,bw=step*.76,y=m+ch-(s.severity/100)*ch;let color="rgba(123,255,178,.85)";if(s.severity>70)color="rgba(255,107,107,.88)";else if(s.severity>55)color="rgba(255,209,102,.9)";ctx.fillStyle=color;ctx.fillRect(x,y,bw,(s.severity/100)*ch);ctx.fillStyle="#dce6f9";ctx.fillText(`${Math.round(s.severity)}%`,x+6,y-8);});ctx.fillStyle="#dce6f9";ctx.font="14px Arial";ctx.fillText("Severidade por trecho",m,28);}
function drawMatrixChart(canvas,result){const ctx=canvas.getContext("2d"),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);drawBackdrop(ctx,w,h);const rows=[["EQ geral",Math.max(...result.bandDelta.map(v=>Math.abs(v)))*180],["Compressão",result.effects.compression],["Sibilância",result.effects.sibilance],["Reverb",result.effects.reverb],["Saturação",result.effects.saturation],["Masking",result.effects.masking],["Estéreo",result.effects.stereo],["Punch",result.effects.transient]],m=50,cw=(w-m*2)/4,ch=(h-m*2)/2;ctx.fillStyle="#dce6f9";ctx.font="14px Arial";ctx.fillText("Leitura rápida do estado geral",m,28);rows.forEach((r,i)=>{const col=i%4,row=Math.floor(i/4),x=m+col*cw,y=m+row*ch,val=Math.max(0,Math.min(100,r[1]));let color="rgba(123,255,178,.25)";if(val>70)color="rgba(255,107,107,.35)";else if(val>50)color="rgba(255,209,102,.30)";ctx.fillStyle=color;ctx.fillRect(x+8,y+8,cw-16,ch-16);ctx.strokeStyle="rgba(255,255,255,.10)";ctx.strokeRect(x+8,y+8,cw-16,ch-16);ctx.fillStyle="#dce6f9";ctx.fillText(r[0],x+22,y+38);ctx.font="bold 28px Arial";ctx.fillText(`${Math.round(val)}%`,x+22,y+78);ctx.font="14px Arial";});}
